
log:
  writers: file                # 输出位置，有两个可选项 —— file 和 stdout。选择 file 会将日志记录到 logger_file 指定的日志文件中，选择 stdout 会将日志输出到标准输出，当然也可以两者同时选择
  logger_level: WARN           # 日志级别，DEBUG、INFO、WARN、ERROR、FATAL
  logger_dir: log/signal.log   # 日志文件目录
  log_format_text: true        # 日志的输出格式，JSON 或者 plaintext，true 会输出成非 JSON 格式，false 会输出成 JSON 格式
  log_rotate_size: 1           # rotate 转存大小，配合 rollingPolicy: size 使用
  log_backup_count: 50          # 当日志文件达到转存标准时，log 系统会将该日志文件进行压缩备份，这里指定了备份文件的最大个数
  log_max_age: 7              # 日志文件保留的最大天数

port: 80
tls:
  port: 443                    # https port
  cert: cert/signaler.pem
  key: cert/signaler.key

redis:
  host: 127.0.0.1
  port: 6379
  dbname: 0
#  password:
  is_cluster: false
  cluster:
#    -
#      host: 127.0.0.1
#      port: 6379
#    -
#      host: 127.0.0.1
#      port: 6380

ratelimit:
  enable: false
  max_rate: 500                # max requests per second

#security:
#  enable: false                # Enable Authentication
#  maxTimeStampAge: 3600        # Timestamp expiration time in seconds
#  token: "%!$y&2"              # Custom token, no more than 8 characters

stats:
  enable: true
#  token: 123456           # Custom token for requesting stats info








